apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kdrsh4o6j-nodejs 
  janus-idp.io/tekton: kdrsh4o6j-nodejs
  backstage.io/kubernetes-id: kdrsh4o6j-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kdrsh4o6j-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml